import type { CardDraft, CardStats, LeadRecord, OwnerProfile } from './types.js'

const now = new Date('2026-08-04T10:24:00.000Z').toISOString()

export const demoOwner: OwnerProfile = {
  uid: 'demo_owner',
  telegramId: '782 453 109',
  firstName: 'Алексей',
  lastName: 'Волков',
  username: 'alexey_cardly',
  photoUrl: '',
  languageCode: 'ru',
  isPremium: true,
  platform: 'Telegram Desktop',
}

export const demoCard: CardDraft = {
  ownerUid: demoOwner.uid,
  profile: {
    displayName: 'Алексей Волков',
    profession: 'Product designer и frontend-разработчик',
    bio: 'Помогаю продуктовым командам превращать сложные сценарии в понятные интерфейсы — от исследования до готового frontend.',
    avatarUrl: '',
    location: 'Москва',
    workFormat: 'hybrid',
    availabilityStatus: 'available',
    availabilityText: 'Доступен для нового проекта',
  },
  primaryAction: {
    type: 'telegram',
    label: 'Написать в Telegram',
    value: 'https://t.me/alexey_cardly',
    enabled: true,
  },
  skills: [
    { id: 'skill-product', label: 'Product design', position: 0 },
    { id: 'skill-research', label: 'UX research', position: 1 },
    { id: 'skill-systems', label: 'Design systems', position: 2 },
    { id: 'skill-figma', label: 'Figma', position: 3 },
    { id: 'skill-vue', label: 'Vue.js', position: 4 },
    { id: 'skill-prototyping', label: 'Prototyping', position: 5 },
  ],
  links: [
    {
      id: 'link-telegram',
      type: 'telegram',
      label: 'Telegram',
      url: 'https://t.me/alexey_cardly',
      enabled: true,
      public: true,
      position: 0,
    },
    {
      id: 'link-site',
      type: 'website',
      label: 'Портфолио',
      url: 'https://example.com/alexey',
      enabled: true,
      public: true,
      position: 1,
    },
    {
      id: 'link-email',
      type: 'email',
      label: 'Email',
      url: 'mailto:alexey@example.com',
      enabled: true,
      public: true,
      position: 2,
    },
  ],
  services: [
    {
      id: 'service-audit',
      title: 'UX-аудит',
      description: 'План улучшений интерфейса за 5 дней',
      priceType: 'from',
      price: 35000,
      currency: 'RUB',
      durationText: '5 дней',
      enabled: true,
      position: 0,
    },
    {
      id: 'service-product',
      title: 'Дизайн продукта',
      description: 'От исследования до готового интерфейса',
      priceType: 'from',
      price: 120000,
      currency: 'RUB',
      durationText: 'от 3 недель',
      enabled: true,
      position: 1,
    },
    {
      id: 'service-consult',
      title: 'Консультация',
      description: 'Разбор продукта и следующего шага',
      priceType: 'fixed',
      price: 8000,
      currency: 'RUB',
      durationText: '80 минут',
      enabled: true,
      position: 2,
    },
  ],
  projects: [
    {
      id: 'project-finflow',
      title: 'Finflow',
      category: 'Fintech',
      description: 'Сервис управления финансами для распределённых команд.',
      coverUrl: '',
      projectUrl: 'https://example.com/finflow',
      enabled: true,
      position: 0,
    },
    {
      id: 'project-city',
      title: 'City Guide',
      category: 'Travel',
      description: 'Городской гид с персональными маршрутами.',
      coverUrl: '',
      projectUrl: 'https://example.com/city-guide',
      enabled: true,
      position: 1,
    },
    {
      id: 'project-educamp',
      title: 'Educamp',
      category: 'Edtech',
      description: 'Платформа для интенсивных учебных программ.',
      coverUrl: '',
      projectUrl: 'https://example.com/educamp',
      enabled: true,
      position: 2,
    },
    {
      id: 'project-studio',
      title: 'Studio OS',
      category: 'SaaS',
      description: 'Операционная система небольшой дизайн-студии.',
      coverUrl: '',
      projectUrl: 'https://example.com/studio-os',
      enabled: true,
      position: 3,
    },
  ],
  appearance: {
    themeId: 'clean',
    accentPreset: 'green',
    avatarShape: 'circle',
    visibleSections: ['skills', 'services', 'projects', 'contacts', 'lead'],
    showLocation: true,
    showAvailability: true,
    showServices: true,
    showProjects: true,
    showSkills: true,
    showContactForm: true,
  },
  publication: { slug: 'alexey', published: true, publishedAt: now, updatedAt: now },
  onboardingCompleted: true,
  createdAt: now,
  updatedAt: now,
  lastPublishedAt: now,
}

export const demoStats: CardStats = {
  totalViews: 1284,
  totalPrimaryClicks: 236,
  totalLinkClicks: 172,
  totalProjectOpens: 98,
  totalLeads: 18,
  totalShares: 41,
  daily: [
    { date: '29 июл', views: 142 },
    { date: '30 июл', views: 168 },
    { date: '31 июл', views: 151 },
    { date: '1 авг', views: 203 },
    { date: '2 авг', views: 176 },
    { date: '3 авг', views: 231 },
    { date: '4 авг', views: 213 },
  ],
  popularActions: [
    { label: 'Telegram', value: 142 },
    { label: 'Проект Finflow', value: 86 },
    { label: 'Сайт', value: 63 },
    { label: 'Поделиться', value: 41 },
  ],
}

export const demoLeads: LeadRecord[] = [
  {
    id: 'lead-maria',
    ownerUid: demoOwner.uid,
    cardSlug: 'alexey',
    senderName: 'Мария Орлова',
    senderContact: '@maria_orlova',
    message: 'Нужен дизайн лендинга для курса',
    source: 'telegram',
    status: 'new',
    createdAt: '2026-08-04T08:15:00.000Z',
  },
  {
    id: 'lead-ilya',
    ownerUid: demoOwner.uid,
    cardSlug: 'alexey',
    senderName: 'Илья Морозов',
    senderContact: 'ilya@example.com',
    message: 'Ищем дизайнера в продуктовую команду',
    source: 'web',
    status: 'read',
    createdAt: '2026-08-03T14:40:00.000Z',
  },
  {
    id: 'lead-anna',
    ownerUid: demoOwner.uid,
    cardSlug: 'alexey',
    senderName: 'Анна Лебедева',
    senderContact: '@annalebedeva',
    message: 'Можно провести UX-аудит?',
    source: 'share',
    status: 'read',
    createdAt: '2026-08-02T09:05:00.000Z',
  },
]
